# Generated by Django 5.0 on 2024-12-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmodel",
            name="toTime",
            field=models.IntegerField(default=16),
        ),
    ]
