# Generated by Django 5.0 on 2024-12-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_groupmodel_totime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmodel",
            name="fromTime",
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name="groupmodel",
            name="toTime",
            field=models.IntegerField(default=20),
        ),
    ]
