# Generated by Django 5.1.4 on 2024-12-29 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_projectpermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.task'),
        ),
    ]
