# Generated by Django 5.1.4 on 2024-12-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_reportmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='prompt',
            field=models.TextField(default='test', max_length=100000),
            preserve_default=False,
        ),
    ]
