# Generated by Django 5.1.4 on 2024-12-30 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_reportmodel_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(max_length=100)),
                ('systemMainPrompt', models.TextField(max_length=100000)),
                ('sendTime', models.IntegerField(choices=[(1, 'Hourly'), (2, 'Dailty'), (3, 'Weekly')])),
            ],
        ),
        migrations.AddField(
            model_name='reportmodel',
            name='sendGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.groupmodel'),
        ),
    ]
