# Generated by Django 5.1.4 on 2024-12-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_groupmodel_firsttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='sendGroup',
            new_name='group',
        ),
    ]
