# Generated by Django 5.1.4 on 2024-12-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_sendgroup_reportmodel_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='sendTime',
            new_name='repeet',
        ),
    ]
