# Generated by Django 5.1.4 on 2024-12-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_sendtime_groupmodel_repeet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmodel',
            old_name='firstTime',
            new_name='sendTime',
        ),
    ]
