# Generated by Django 5.1.4 on 2024-12-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_firsttime_groupmodel_sendtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='verbose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
