# Generated by Django 5.1.4 on 2024-12-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_groupmodel_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='projects',
            field=models.ManyToManyField(null=True, to='core.project'),
        ),
    ]
