# Generated by Django 5.1.4 on 2024-12-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_groupmodel_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='projects',
            field=models.ManyToManyField(blank=True, to='core.project'),
        ),
    ]
