# Generated by Django 5.1.4 on 2024-12-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_groupmodel_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
