# Generated by Django 5.1.4 on 2024-12-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_reportmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='repeet',
            field=models.DurationField(),
        ),
    ]
