# Generated by Django 5.1.4 on 2024-12-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_groupmodel_repeet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='repeet',
            field=models.DurationField(default=1000000),
        ),
    ]
