# Generated by Django 5.1.4 on 2024-12-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_groupmodel_repeet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='repeet',
        ),
        migrations.AddField(
            model_name='groupmodel',
            name='repeetHour',
            field=models.IntegerField(default=1),
        ),
    ]
