# Generated by Django 5.1.4 on 2024-12-30 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_groupmodel_repeet_groupmodel_repeethour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmodel',
            name='sendTime',
        ),
    ]
